Fix undefined callback
~$ lifxcli -vT
/usr/local/lib/node_modules/lifx-client/lib/index.js:137
  lifx.togglePower(selection, cb);
                              ^

ReferenceError: cb is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/lifx-client/lib/index.js:137:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/lifx-client/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)


Replaced undefined variable cb with console.log. Works great now.